In [1]:
import pandas as pd

In [2]:
agriculture_data = pd.read_excel("../data/agriculture 04.19.2025.xlsx", header=[0, 1])

In [3]:
agriculture_data.columns = ['_'.join([str(i).strip() for i in col if pd.notna(i)]) for col in agriculture_data.columns.values]

In [4]:
agriculture_data.head()

,Unnamed: 0_level_0_Unnamed: 0_level_1,Unnamed: 1_level_0_Unnamed: 1_level_1,PAPINE_Lowest,PAPINE_Highest,PAPINE_Most\nFreq.,CORONATION_Lowest,CORONATION_Highest,CORONATION_Most Freq.,CROSS ROADS_Lowest,CROSS ROADS_Highest,...,BARBICAN\nROAD_Hi-Lo,CONSTANT SPRING_Hi-Lo,CONSTANT SPRING_Select\nGrocers,HARBOUR\nVIEW_Shoppers\nFair,RED HILLS ROAD_Lee's Food\nFair,RED HILLS ROAD_Price\nSmart,PORTMORE_Progressive\nFoods,PORTMORE_Mega\nMart,PORTMORE_Joong,PORTMORE_Hi-Lo
0,Broccoli,Imported,NaN,NaN,NaN,2200.0,2200.0,2200.00,NaN,NaN,...,3060.89,3060.89,3000.0,1526.20,2480.18,NaN,NaN,2800.0,2250.0,3060.89
1,Cabbage (Green),Local,330.0,440.0,403.33,110.0,264.0,162.80,330.0,330.0,...,1447.16,745.34,495.0,330.00,634.93,999.0,330.00,580.0,660.0,745.34
2,Cabbage (Red),Imported,NaN,NaN,NaN,1100.0,1100.0,1100.00,NaN,NaN,...,1157.01,1157.00,1250.0,693.80,925.93,NaN,481.80,1360.0,1167.0,1157.01
3,Callaloo,Shredded,660.0,770.0,715.00,440.0,550.0,513.33,660.0,660.0,...,772.20,772.20,NaN,659.98,554.40,449.0,659.98,627.0,NaN,569.80
4,Callaloo,Whole,616.0,660.0,645.33,330.0,330.0,330.00,660.0,660.0,...,519.00,NaN,NaN,450.00,550.00,NaN,450.00,NaN,NaN,519.00

In [5]:
agriculture_data['Commodity'] = agriculture_data['Unnamed: 0_level_0_Unnamed: 0_level_1'].astype(str) + ' ' + agriculture_data['Unnamed: 1_level_0_Unnamed: 1_level_1'].astype(str)

In [6]:
agriculture_data.drop(['Unnamed: 0_level_0_Unnamed: 0_level_1', 'Unnamed: 1_level_0_Unnamed: 1_level_1', 'PAPINE_Lowest','PAPINE_Highest','CORONATION_Lowest', 'CORONATION_Highest','CROSS ROADS_Lowest', 'CROSS ROADS_Highest'], axis=1, inplace=True)

In [7]:
agriculture_data = agriculture_data[['Commodity'] + [col for col in agriculture_data.columns if col != 'Commodity']]

In [8]:
agriculture_data.rename(
    columns=lambda col: col.replace("Most Freq.", "Market") if col.endswith("Most Freq.") else col,
    inplace=True
)

In [9]:
agriculture_data = agriculture_data.melt(id_vars=['Commodity'], var_name='Market', value_name='Price')

In [10]:
agriculture_data['Market'] = agriculture_data['Market'].str.replace('_', ' ', regex=False)

In [11]:
agriculture_data['Market'] = agriculture_data['Market'].str.replace('\n', ' ', regex=False)

In [12]:
unique_markets = agriculture_data['Market'].unique()
print(unique_markets)

['PAPINE Most Freq.' 'CORONATION Market' 'CROSS ROADS Most Freq.'
 'CROSS ROADS Sampars' 'CROSS ROADS Hi-Lo' 'WATERLOO ROAD Mega Mart'
 'NEW KINGSTON John R Wong' 'HALF-WAY TREE Brooklyn'
 'WASHINGTON BOULEVARD Shoppers Fair' 'DUHANEY PARK Shoppers Fair'
 'LIGUANEA General Foods' 'LIGUANEA General Foods.1'
 'LIGUANEA Shoppers Fair' 'BARBICAN ROAD Loshusan' 'BARBICAN ROAD Hi-Lo'
 'CONSTANT SPRING Hi-Lo' 'CONSTANT SPRING Select Grocers'
 'HARBOUR VIEW Shoppers Fair' "RED HILLS ROAD Lee's Food Fair"
 'RED HILLS ROAD Price Smart' 'PORTMORE Progressive Foods'
 'PORTMORE Mega Mart' 'PORTMORE Joong' 'PORTMORE Hi-Lo']

In [13]:
unique_commodity = agriculture_data['Commodity'].unique()
print(unique_commodity)

['Broccoli Imported' 'Cabbage (Green) Local' 'Cabbage (Red) Imported'
 'Callaloo Shredded' 'Callaloo Whole' 'Cantaloupe Local' 'Carrot Local'
 'Cauliflower Local' 'Coco Local' 'Cucumber Local' 'Dasheen Local'
 'Escallion Local' 'Ginger Local' 'Green Banana Local' 'Gungo Peas Dry'
 'Honeydew Melon Local' 'Irish Potato Local' 'Lettuce Iceberg (Local)'
 'Lettuce Romaine (Local)' 'Okra Local' 'Onion Local' 'Onion Imported'
 'Pak Choi Local' 'Papaya Local' 'Hot Pepper Scotch Bonnet'
 'Hot Pepper West Indian Red' 'Pineapple Cow Boy (Local)'
 'Pineapple MD 2 (Local)' 'Plantain Ripe (Local)' 'Plantain Green (Local)'
 'Pumpkin Local' 'String Beans Local' 'Sweet Pepper (Green) Local'
 'Sweet Pepper (Red) Local' 'Sweet Pepper (Yellow) Local'
 'Sweet Potato Local' 'Thyme Local' 'Tomatoes(Plummy) Local'
 'Tomatoes(Salad) Local' 'Turmeric Local' 'Watermelon Local' 'Yam Yellow'
 'Yam Negro']

In [14]:
agriculture_data.to_json("../data/agriculture_data.json", orient="records", indent=2)

In [17]:
agriculture_data.sample(10)

                       Commodity                          Market    Price
960               Gungo Peas Dry                  PORTMORE Joong  1122.00
610                   Coco Local             BARBICAN ROAD Hi-Lo  1157.89
708                  Onion Local  CONSTANT SPRING Select Grocers      NaN
1006     Lettuce Iceberg (Local)                  PORTMORE Hi-Lo  1350.88
281                 Papaya Local        NEW KINGSTON John R Wong   664.65
684               Turmeric Local           CONSTANT SPRING Hi-Lo  1073.01
634   Sweet Pepper (Green) Local             BARBICAN ROAD Hi-Lo  2092.22
560        Cabbage (Green) Local          BARBICAN ROAD Loshusan   495.00
767                  Thyme Local      HARBOUR VIEW Shoppers Fair  2639.90
15          Honeydew Melon Local               PAPINE Most Freq.      NaN